/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.sql.*;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM2Alu2
 */
public class JDialogTienda extends javax.swing.JDialog {
    private int unidades = 0;
    private Map<String, Object[]> carrito = new LinkedHashMap<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogTienda.class.getName());

    /**
     * Creates new form Tienda
     */
    DefaultTableModel dtm;
    public JDialogTienda(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ajustarImagenLogo();
        
        dtm = new DefaultTableModel();
        dtm.addColumn("Nombre");
        dtm.addColumn("Descripción");
        dtm.addColumn("Tipo");
        dtm.addColumn("Precio");

        jTableProductos.setModel(dtm);
        
        try (Connection con = Conexion.getConexion()) {
        String sqlProducto = "SELECT nombre, descripcion, tipo, precio FROM producto";
        PreparedStatement ps = con.prepareStatement(sqlProducto);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] fila = new Object[4];
            fila[0] = rs.getString("nombre");
            fila[1] = rs.getString("descripcion");
            fila[2] = rs.getString("tipo");
            double precio = rs.getDouble("precio");
            fila[3] = precio+"€";
            dtm.addRow(fila);
        }
        
        jTableProductos.getColumnModel().getColumn(0).setPreferredWidth(160);
        jTableProductos.getColumnModel().getColumn(1).setPreferredWidth(290);
        jTableProductos.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTableProductos.getColumnModel().getColumn(3).setPreferredWidth(40);
      
        jTableProductos.getTableHeader().setForeground(new Color(255, 153, 0));
        jTableProductos.getTableHeader().setFont(new Font("Candara", Font.BOLD, 14));

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipoProducto = new javax.swing.JComboBox<>();
        jLabelPrecioMaximo = new javax.swing.JLabel();
        jSliderPrecio = new javax.swing.JSlider();
        jToggleButtonBuscar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelNumeroProductos = new javax.swing.JLabel();
        jLabelPrecioTotal = new javax.swing.JLabel();
        jButtonAnadir = new javax.swing.JButton();
        jButtonCarrito = new javax.swing.JButton();
        jToggleButtonPago = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(8, 1));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Filtrar por:");
        jPanel2.add(jLabel1);

        jLabel4.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 164, 175));
        jLabel4.setText("NOMBRE");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel4);

        jTextFieldBusqueda.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jPanel2.add(jTextFieldBusqueda);

        jLabel3.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 164, 175));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText(" TIPO DE PRODUCTO");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel3);

        jComboBoxTipoProducto.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jComboBoxTipoProducto.setForeground(new java.awt.Color(105, 211, 183));
        jComboBoxTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Esencial", "Medicina", "Juguete" }));
        jPanel2.add(jComboBoxTipoProducto);

        jLabelPrecioMaximo.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabelPrecioMaximo.setForeground(new java.awt.Color(52, 164, 175));
        jLabelPrecioMaximo.setText(" PRECIO MÁXIMO: 50€");
        jLabelPrecioMaximo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabelPrecioMaximo);

        jSliderPrecio.setMaximum(50);
        jSliderPrecio.setMinimum(3);
        jSliderPrecio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPrecioStateChanged(evt);
            }
        });
        jPanel2.add(jSliderPrecio);

        jToggleButtonBuscar.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jToggleButtonBuscar.setForeground(new java.awt.Color(255, 153, 0));
        jToggleButtonBuscar.setText("BUSCAR");
        jToggleButtonBuscar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jToggleButtonBuscar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jToggleButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButtonBuscar);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(133, 210, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VetPet Store");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabelNumeroProductos.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabelNumeroProductos.setForeground(new java.awt.Color(52, 164, 175));
        jLabelNumeroProductos.setText("Productos en el carrito: 0");
        jPanel3.add(jLabelNumeroProductos);

        jLabelPrecioTotal.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabelPrecioTotal.setForeground(new java.awt.Color(255, 153, 0));
        jLabelPrecioTotal.setText("Total: 0.0€");
        jPanel3.add(jLabelPrecioTotal);

        jButtonAnadir.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jButtonAnadir.setForeground(new java.awt.Color(105, 211, 183));
        jButtonAnadir.setText("Añadir al carrito");
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAnadir);

        jButtonCarrito.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jButtonCarrito.setForeground(new java.awt.Color(105, 211, 183));
        jButtonCarrito.setText("Ver carrito");
        jButtonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarritoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCarrito);

        jToggleButtonPago.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jToggleButtonPago.setForeground(new java.awt.Color(255, 153, 0));
        jToggleButtonPago.setText("Pagar");
        jToggleButtonPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPagoActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButtonPago);

        jTableProductos.setBackground(new java.awt.Color(255, 255, 255));
        jTableProductos.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTableProductos.setForeground(new java.awt.Color(52, 164, 175));
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jTableProductos.setRowHeight(30);
        jTableProductos.setRowMargin(5);
        jTableProductos.setSelectionBackground(new java.awt.Color(52, 164, 175));
        jTableProductos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTableProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTableProductos.getModel();
        modelo.setRowCount(0);
    }
    
    private void jSliderPrecioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPrecioStateChanged
        int valor = jSliderPrecio.getValue();
        String texto= String.valueOf(valor);
        jLabelPrecioMaximo.setText("PRECIO MÁXIMO: " + texto + "€");
    }//GEN-LAST:event_jSliderPrecioStateChanged

    private void jToggleButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBuscarActionPerformed
        int valorSlider = jSliderPrecio.getValue();
        String valorCombo = jComboBoxTipoProducto.getSelectedItem().toString();
        String valorNombre = jTextFieldBusqueda.getText().trim();

        String sql = "";
        PreparedStatement psB = null;

        try (Connection con = Conexion.getConexion()) {
            if (valorNombre.isEmpty()) {
                if (valorCombo.equals("Todos")) {
                    sql = "SELECT * FROM producto WHERE precio <= ?";
                    psB = con.prepareStatement(sql);
                    psB.setInt(1, valorSlider);
                } else {
                    sql = "SELECT * FROM producto WHERE precio <= ? AND tipo = ?";
                    psB = con.prepareStatement(sql);
                    psB.setInt(1, valorSlider);
                    psB.setString(2, valorCombo);
                }
            } else if (valorCombo.equals("Todos")) {
                sql = "SELECT * FROM producto WHERE precio <= ? AND nombre LIKE ?";
                psB = con.prepareStatement(sql);
                psB.setInt(1, valorSlider);
                psB.setString(2, valorNombre + "%");
            } else {
                sql = "SELECT * FROM producto WHERE precio <= ? AND tipo = ? AND nombre LIKE ?";
                psB = con.prepareStatement(sql);
                psB.setInt(1, valorSlider);
                psB.setString(2, valorCombo);
                psB.setString(3, valorNombre + "%");
            }

            ResultSet rsB = psB.executeQuery();
            java.util.List<Object[]> filas = new java.util.ArrayList<>();
            while (rsB.next()) {
                Object[] fila = new Object[4];
                fila[0] = rsB.getString("nombre");
                fila[1] = rsB.getString("descripcion");
                fila[2] = rsB.getString("tipo");
                fila[3] = rsB.getDouble("precio") + "€";

                filas.add(fila);
            }
            if (filas.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún producto que coincida con los parámetros de búsqueda.", "Sin resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            limpiarTabla();

            for (Object[] fila : filas) {
                dtm.addRow(fila);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jToggleButtonBuscarActionPerformed

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        if (jTableProductos.getSelectedRowCount() > 0) {
            int[] seleccionados = jTableProductos.getSelectedRows();
            boolean alMenosUnoAnadido = false;
            int productosAnadidos=0;

            for (int fila : seleccionados) {
                String nombre = jTableProductos.getValueAt(fila, 0).toString();
                String precioStr = jTableProductos.getValueAt(fila, 3).toString().replace("€", "");
                double precio = Double.parseDouble(precioStr);

                int cantidadEnCarrito = carrito.containsKey(nombre) ? (Integer) carrito.get(nombre)[0] : 0;

                if (!hayStockDisponible(nombre, cantidadEnCarrito + 1)) {
                    JOptionPane.showMessageDialog(this, "No quedan unidades disponibles para " + nombre);
                    continue;
                }

                if (carrito.containsKey(nombre)) {
                    carrito.get(nombre)[0] = (Integer) carrito.get(nombre)[0] + 1;
                } else {
                    carrito.put(nombre, new Object[]{1, precio});
                }
                productosAnadidos++;
                alMenosUnoAnadido = true;
            }

            if (alMenosUnoAnadido) {
                if (productosAnadidos==1)
                    JOptionPane.showMessageDialog(this, "Se ha añadido el producto seleccionado al carrito.");
                else
                    JOptionPane.showMessageDialog(this, "Se han añadido los productos seleccionados al carrito.");
            }

            actualizarLabels();
        } else {
            JOptionPane.showMessageDialog(this, "No has seleccionado ningún producto.");
        }
    }//GEN-LAST:event_jButtonAnadirActionPerformed

    private void jButtonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarritoActionPerformed
        if (carrito.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío.");
            return;
        }

        JDialog dialogCarrito = new JDialog(this, "Carrito de Compras", true);
        dialogCarrito.setSize(400, 300);
        dialogCarrito.setLocationRelativeTo(this);
        dialogCarrito.setLayout(new BorderLayout());

        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        for (Map.Entry<String, Object[]> entry : carrito.entrySet()) {
            String nombre = entry.getKey();
            int cantidad = (Integer) entry.getValue()[0];
            double precioUnitario = (Double) entry.getValue()[1];
            double precioTotal = cantidad * precioUnitario;

            if (cantidad > 1) {
                modeloLista.addElement(nombre + " (x" + cantidad + ") - " + precioTotal + "€");
            } else {
                modeloLista.addElement(nombre + " - " + precioTotal + "€");
            }
        }

        JList<String> listaCarrito = new JList<>(modeloLista);
        JScrollPane scroll = new JScrollPane(listaCarrito);
        dialogCarrito.add(scroll, BorderLayout.CENTER);

        JPanel panelBotones = new JPanel();
        JButton btnQuitar = new JButton("Quitar productos");
        JButton btnModificarValores = new JButton("Alterar cantidades");
        JButton btnSalir = new JButton("OK");
        panelBotones.add(btnQuitar);
        panelBotones.add(btnModificarValores);
        panelBotones.add(btnSalir);
        dialogCarrito.add(panelBotones, BorderLayout.SOUTH);

        btnQuitar.addActionListener(e -> {
            int[] seleccionados = listaCarrito.getSelectedIndices();
            if (seleccionados.length == 0) {
                JOptionPane.showMessageDialog(dialogCarrito, "Selecciona los productos que quieras quitar.");
                return;
            }

            List<String> keys = new ArrayList<>(carrito.keySet());
            for (int i = seleccionados.length - 1; i >= 0; i--) {
                String key = keys.get(seleccionados[i]);
                carrito.remove(key);
                modeloLista.remove(seleccionados[i]);
            }
            actualizarLabels();
        });

        // Modificar cantidades
        btnModificarValores.addActionListener(e -> {
            int[] seleccionados = listaCarrito.getSelectedIndices();
            if (seleccionados.length == 0) return;

            JDialog modificarDialog = new JDialog(dialogCarrito, "Modificar Cantidades", true);
            modificarDialog.setSize(300, 100);
            modificarDialog.setLocationRelativeTo(dialogCarrito);
            modificarDialog.setLayout(new FlowLayout());

            JButton btnSumar = new JButton("+");
            JButton btnRestar = new JButton("-");
            JButton btnCerrar = new JButton("OK");

            modificarDialog.add(btnSumar);
            modificarDialog.add(btnRestar);
            modificarDialog.add(btnCerrar);

            btnSumar.addActionListener(ev -> {
                List<String> keys = new ArrayList<>(carrito.keySet());
                for (int i : seleccionados) {
                    String key = keys.get(i);
                    // Verificar stock antes de aumentar
                    int cantidadActual = (Integer) carrito.get(key)[0];
                    if (!hayStockDisponible(key, cantidadActual + 1)) {
                        JOptionPane.showMessageDialog(modificarDialog, "No quedan unidades disponibles para " + key);
                        continue;
                    }
                    carrito.get(key)[0] = cantidadActual + 1;
                }
                modeloLista.clear();
                carrito.forEach((k, v) -> {
                    int cant = (Integer) v[0];
                    double precio = (Double) v[1];
                    modeloLista.addElement(cant > 1 ? k + " (x" + cant + ") - " + (cant*precio) + "€" : k + " - " + (cant*precio) + "€");
                });
                actualizarLabels();
            });

            btnRestar.addActionListener(ev -> {
                List<String> keys = new ArrayList<>(carrito.keySet());
                for (int i : seleccionados) {
                    String key = keys.get(i);
                    int cantidadActual = (Integer) carrito.get(key)[0];
                    if (cantidadActual > 1) {
                        carrito.get(key)[0] = cantidadActual - 1;
                    } else {
                        carrito.remove(key);
                    }
                }
                modeloLista.clear();
                carrito.forEach((k, v) -> {
                    int cant = (Integer) v[0];
                    double precio = (Double) v[1];
                    modeloLista.addElement(cant > 1 ? k + " (x" + cant + ") - " + (cant*precio) + "€" : k + " - " + (cant*precio) + "€");
                });
                actualizarLabels();
            });

            btnCerrar.addActionListener(ev -> modificarDialog.dispose());
            modificarDialog.setVisible(true);
        });

        btnSalir.addActionListener(e -> dialogCarrito.dispose());
        dialogCarrito.setVisible(true);
    }//GEN-LAST:event_jButtonCarritoActionPerformed

    private void jToggleButtonPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPagoActionPerformed
        if (carrito.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío, añada más productos.");
            return;
        }
        double totalCompra = 0.0;
        StringBuilder resumen = new StringBuilder();

        try (Connection con = Conexion.getConexion()) {
            for (Map.Entry<String, Object[]> entry : carrito.entrySet()) {
                String nombre = entry.getKey();
                int cantidad = (Integer) entry.getValue()[0];
                double precioUnitario = (Double) entry.getValue()[1];
                double precioTotal = cantidad * precioUnitario;

                String sqlCheck = "SELECT unidades FROM producto WHERE nombre=?";
                PreparedStatement psCheck = con.prepareStatement(sqlCheck);
                psCheck.setString(1, nombre);
                ResultSet rsCheck = psCheck.executeQuery();
                if (rsCheck.next()) {
                    int unidadesDisponibles = rsCheck.getInt("unidades");
                    if (cantidad > unidadesDisponibles) {
                        JOptionPane.showMessageDialog(this, 
                            "No hay suficiente stock para " + nombre + ". Solo quedan " + unidadesDisponibles + " unidades.");
                        return;
                    }
                }
                if (cantidad > 1) {
                    resumen.append(nombre).append(" (x").append(cantidad).append(") - ").append(precioTotal).append("€\n");
                } else {
                    resumen.append(nombre).append(" - ").append(precioTotal).append("€\n");
                }
                totalCompra += precioTotal;
            }
            resumen.append("\nTotal a pagar: ").append(totalCompra).append("€");

            int opcion = JOptionPane.showConfirmDialog(this, resumen.toString() + "\n\n¿Quiere pagar?", "Confirmar pago", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                for (Map.Entry<String, Object[]> entry : carrito.entrySet()) {
                    String nombre = entry.getKey();
                    int cantidad = (Integer) entry.getValue()[0];

                    String sqlUpdate = "UPDATE producto SET unidades = unidades - ? WHERE nombre=?";
                    PreparedStatement psUpdate = con.prepareStatement(sqlUpdate);
                    psUpdate.setInt(1, cantidad);
                    psUpdate.setString(2, nombre);
                    psUpdate.executeUpdate();
                }

                JOptionPane.showMessageDialog(this, "Gracias por su compra");
                carrito.clear();
                actualizarLabels();
                this.dispose();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jToggleButtonPagoActionPerformed

    private void actualizarLabels() {
        int totalProductos = 0;
        double totalPrecio = 0.0;

        for (Object[] valores : carrito.values()) {
            int cantidad = (Integer) valores[0];
            double precioUnitario = (Double) valores[1];
            totalProductos += cantidad;
            totalPrecio += cantidad * precioUnitario;
        }
        jLabelNumeroProductos.setText("Productos en el carrito: " + totalProductos);
        jLabelPrecioTotal.setText("Total: " + totalPrecio + "€");
    }
    
    private boolean hayStockDisponible(String nombre, int cantidadSolicitada) {
        try (Connection con = Conexion.getConexion()) {
            String sql = "SELECT unidades FROM producto WHERE nombre=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, nombre);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int unidadesDisponibles = rs.getInt("unidades");
                return unidadesDisponibles >= cantidadSolicitada;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    private void ajustarImagenLogo() {
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);
        logo.setIcon(iconoEscalado);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogTienda dialog = new JDialogTienda(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JButton jButtonCarrito;
    private javax.swing.JComboBox<String> jComboBoxTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNumeroProductos;
    private javax.swing.JLabel jLabelPrecioMaximo;
    private javax.swing.JLabel jLabelPrecioTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderPrecio;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldBusqueda;
    private javax.swing.JToggleButton jToggleButtonBuscar;
    private javax.swing.JToggleButton jToggleButtonPago;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}