/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;

import Veterinaria.Conexion;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
;
/**
 *
 * @author DAM2Alu13
 */
public class JDialogTableVeterinarios extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogTableVeterinarios.class.getName());
    private TableRowSorter<TableModel> order;

    /**
     * Creates new form JDialogTableVeterinarios
     */
    public JDialogTableVeterinarios(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarUsuariosEnTabla();
        order = new TableRowSorter<>(jTableVeterinarios.getModel());
        jTableVeterinarios.setRowSorter(order);

    }
    
   private void cargarUsuariosEnTabla() {
    
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[][] {},
        new String[] { "ID", "Nombre", "Apellidos", "Teléfono", "Correo", "Usuario" }
    ) {
        
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };

    String sql = "SELECT id, nombre, apellidos, telefono, correo, usuario FROM usuario WHERE rol = 'Veterinario'";

    try (Connection con = Conexion.getConexion();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(sql)) {

        while (rs.next()) {
            Object[] fila = new Object[7];
            fila[0] = rs.getString("id");
            fila[1] = rs.getString("nombre");
            fila[2] = rs.getString("apellidos");
            fila[3] = rs.getString("telefono");
            fila[4] = rs.getString("correo");
            fila[5] = rs.getString("usuario");
            

            modelo.addRow(fila);
        }

        jTableVeterinarios.setModel(modelo);
        jTableVeterinarios.setDefaultEditor(Object.class, null); // Refuerzo: desactiva edición

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
} 

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jLabelBuscarDNI = new javax.swing.JLabel();
        jTextFieldBuscaDNI = new javax.swing.JTextField();
        jLabelBuscarNombre = new javax.swing.JLabel();
        jTextFieldBuscanombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeterinarios = new javax.swing.JTable();
        jLabelBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jLabelBuscarDNI.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBuscarDNI.setText("Buscar por DNI");

        jTextFieldBuscaDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaDNIActionPerformed(evt);
            }
        });

        jLabelBuscarNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBuscarNombre.setText("Buscar por nombre");

        jTextFieldBuscanombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscanombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButtonSalir)
                .addGap(28, 28, 28)
                .addComponent(jButtonInsertar)
                .addGap(30, 30, 30)
                .addComponent(jButtonBorrar)
                .addGap(62, 62, 62)
                .addComponent(jLabelBuscarDNI)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldBuscaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabelBuscarNombre)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldBuscanombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonInsertar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jLabelBuscarDNI)
                    .addComponent(jTextFieldBuscaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscarNombre)
                    .addComponent(jTextFieldBuscanombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableVeterinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellidos", "Telefono", "Correo", "Usuario"
            }
        ));
        jScrollPane1.setViewportView(jTableVeterinarios);
        if (jTableVeterinarios.getColumnModel().getColumnCount() > 0) {
            jTableVeterinarios.getColumnModel().getColumn(5).setHeaderValue("Usuario");
        }

        jLabelBienvenida.setFont(new java.awt.Font("Candara", 2, 36)); // NOI18N
        jLabelBienvenida.setForeground(new java.awt.Color(133, 210, 204));
        jLabelBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBienvenida.setText("Veterinarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        
        JDialogpanelinsertarvet jpi = new JDialogpanelinsertarvet(JDialogTableVeterinarios.this, true);
        jpi.setVisible(true);
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        
        JDialogpanelBorrarvet jdb = new JDialogpanelBorrarvet(JDialogTableVeterinarios.this, true);
        jdb.setVisible(true);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldBuscaDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaDNIActionPerformed
         try {
        RowFilter<Object, Object> rf = RowFilter.regexFilter(
            "^" + jTextFieldBuscaDNI.getText(),  
            0                                    
        );
        order.setRowFilter(rf);
    } catch (Exception pse) {
        System.out.println("Ha ocurrido un error");
    } 
    }//GEN-LAST:event_jTextFieldBuscaDNIActionPerformed

    private void jTextFieldBuscanombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscanombreActionPerformed
        try {
        RowFilter<Object, Object> rf = RowFilter.regexFilter(
            "^" + jTextFieldBuscanombre.getText(),  
            1                                    
        );
        order.setRowFilter(rf);
    } catch (Exception pse) {
        System.out.println("Ha ocurrido un error");
    } 
    }//GEN-LAST:event_jTextFieldBuscanombreActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogTableVeterinarios dialog = new JDialogTableVeterinarios(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JLabel jLabelBuscarDNI;
    private javax.swing.JLabel jLabelBuscarNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeterinarios;
    private javax.swing.JTextField jTextFieldBuscaDNI;
    private javax.swing.JTextField jTextFieldBuscanombre;
    // End of variables declaration//GEN-END:variables
}
