/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import Veterinaria.Conexion;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;


/**
 *
 * @author julia
 */
public class JDialoginsertarmascotas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialoginsertarmascotas.class.getName());
    
    private File imagenSeleccionada = null;

    /**
     * Creates new form JDialoginsertarmascotas
     */
    public JDialoginsertarmascotas(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabelIniciarSesion = new javax.swing.JLabel();
        jPanelRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldespecie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldedad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldsexo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldpeso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldhistorial = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonsubirimagen = new javax.swing.JButton();
        jButtonsiguiente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N

        jLabelIniciarSesion.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabelIniciarSesion.setForeground(new java.awt.Color(52, 164, 175));
        jLabelIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIniciarSesion.setText("insertar mascotas");

        jPanelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegistro.setLayout(new java.awt.GridLayout(8, 2, 0, 10));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 211, 183));
        jLabel2.setText("Nombre");
        jPanelRegistro.add(jLabel2);
        jPanelRegistro.add(jTextFieldnombre);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(105, 211, 183));
        jLabel3.setText("Especie");
        jPanelRegistro.add(jLabel3);
        jPanelRegistro.add(jTextFieldespecie);

        jLabel7.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(105, 211, 183));
        jLabel7.setText("Edad");
        jPanelRegistro.add(jLabel7);
        jPanelRegistro.add(jTextFieldedad);

        jLabel8.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(105, 211, 183));
        jLabel8.setText("Sexo");
        jPanelRegistro.add(jLabel8);
        jPanelRegistro.add(jTextFieldsexo);

        jLabel9.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(105, 211, 183));
        jLabel9.setText("Peso");
        jPanelRegistro.add(jLabel9);
        jPanelRegistro.add(jTextFieldpeso);

        jLabel10.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(105, 211, 183));
        jLabel10.setText("Vacunas");
        jPanelRegistro.add(jLabel10);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacunado", "no vacunado" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jComboBoxTipo);

        jLabel11.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(105, 211, 183));
        jLabel11.setText("Historial");
        jPanelRegistro.add(jLabel11);
        jPanelRegistro.add(jTextFieldhistorial);

        jLabel12.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(105, 211, 183));
        jLabel12.setText("Subir imagen");
        jPanelRegistro.add(jLabel12);

        jButtonsubirimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubirimagenActionPerformed(evt);
            }
        });
        jPanelRegistro.add(jButtonsubirimagen);

        jButtonsiguiente.setText("Siguente");
        jButtonsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsiguienteActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonsiguiente)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButtonsiguiente))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        String tipo = (String) jComboBoxTipo.getSelectedItem();
    }//GEN-LAST:event_jComboBoxTipoActionPerformed
    
    private void jButtonsubirimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubirimagenActionPerformed
   JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "png", "jpg", "jpeg"));
    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        imagenSeleccionada = fileChooser.getSelectedFile();
        // Usa un JLabel dedicado, por ejemplo jLabelFoto
        jLabel12.setIcon(new ImageIcon(imagenSeleccionada.getAbsolutePath())); 
    }
    }//GEN-LAST:event_jButtonsubirimagenActionPerformed

    private void jButtonsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsiguienteActionPerformed
  String nombre = jTextFieldnombre.getText();
  String especie= jTextFieldespecie.getText();
    String edad   = jTextFieldedad.getText();
    String sexo   = jTextFieldsexo.getText();
    String pesoStr = jTextFieldpeso.getText();
    String vacunasStr = jComboBoxTipo.getSelectedItem().toString(); // "Vacunado" / "no vacunado"
    String historial = jTextFieldhistorial.getText(); // JTextField

    if (nombre.isEmpty() || edad.isEmpty() || sexo.isEmpty() || pesoStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        double peso = Double.parseDouble(pesoStr);
        int vacunas = vacunasStr.equalsIgnoreCase("Vacunado") ? 1 : 0;

        insertarMascota(nombre, especie, edad, sexo, peso, vacunas, historial, imagenSeleccionada);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Peso no válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonsiguienteActionPerformed

   private void insertarMascota(String nombre, String especie, String edad, String sexo, double peso,
                             int vacunas, String historial, File imagen) {

    String sql = "INSERT INTO mascota (nombre, especie, edad, sexo, peso, vacunas, historial, foto) "
               + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

    try (Connection con = Conexion.getConexion();
         PreparedStatement ps = con.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS)) {

        ps.setString(1, nombre);
        ps.setString(2, especie);   // <-- nuevo campo
        ps.setString(3, edad);
        ps.setString(4, sexo);
        ps.setDouble(5, peso);
        ps.setInt(6, vacunas);
        ps.setString(7, historial);

        if (imagen != null) {
            byte[] bytes = java.nio.file.Files.readAllBytes(imagen.toPath());
            ps.setBytes(8, bytes);
        } else {
            ps.setNull(8, java.sql.Types.BLOB);
        }

        int filas = ps.executeUpdate();
        if (filas > 0) {
            try (java.sql.ResultSet rs = ps.getGeneratedKeys()) {
                if (rs.next()) {
                    long idGenerado = rs.getLong(1);
                    JOptionPane.showMessageDialog(this, "Mascota insertada. ID: " + idGenerado, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Mascota insertada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo insertar la mascota.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException | IOException e) {
        JOptionPane.showMessageDialog(this, "Error al insertar mascota: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        logger.log(java.util.logging.Level.SEVERE, "Error al insertar mascota", e);
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialoginsertarmascotas dialog = new JDialoginsertarmascotas(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonsiguiente;
    private javax.swing.JButton jButtonsubirimagen;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JTextField jTextFieldedad;
    private javax.swing.JTextField jTextFieldespecie;
    private javax.swing.JTextField jTextFieldhistorial;
    private javax.swing.JTextField jTextFieldnombre;
    private javax.swing.JTextField jTextFieldpeso;
    private javax.swing.JTextField jTextFieldsexo;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
