/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;
import Veterinaria.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
/**
 *
 * @author Administrador
 */
public class JDialogInicio extends javax.swing.JDialog {
    private String usuario;
    private String contrasena;
    private String idCliente;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogInicio.class.getName());

    /**
     * Creates new form JDialogInicio
     */
    public JDialogInicio(java.awt.Frame parent, boolean modal, String usuario, String contrasena) {
        super(parent, modal);
        initComponents();

        ajustarImagenLogo();
        ajustarImagenSalida();
        this.contrasena = contrasena;

        try (Connection con = Conexion.getConexion()) {
            String sql = "SELECT nombre, rol, id FROM usuario WHERE usuario=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, usuario);

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String nombre = rs.getString("nombre");
                String rol = rs.getString("rol");
                idCliente = rs.getString("id");

                jLabelTitulo.setText("Bienvenid@ " + nombre + ". ¿Qué quieres hacer hoy?");
                jLabelTitulo.revalidate();
                jLabelTitulo.repaint();

                if ("Cliente".equalsIgnoreCase(rol)) {
                    jButtonPanel.setVisible(false);
                    jButtonPanel.setEnabled(false);
                } else { // Veterinario o Administrador
                    jButtonPanel.setVisible(true);
                    jButtonPanel.setEnabled(true);
                }
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonSalida = new javax.swing.JToggleButton();
        jButtonPanel = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jToggleAdoptar = new javax.swing.JToggleButton();
        jToggleTienda = new javax.swing.JToggleButton();
        jButtonHistorialMascota = new javax.swing.JButton();
        jButtonAgendarCita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(800, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabelTitulo.setFont(new java.awt.Font("Candara", 2, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(52, 164, 175));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Título de la aplicación.");
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(602, 80));

        jButtonSalida.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });

        jButtonPanel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButtonPanel.setForeground(new java.awt.Color(52, 164, 175));
        jButtonPanel.setText("Panel de control");
        jButtonPanel.setPreferredSize(new java.awt.Dimension(120, 50));
        jButtonPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPanelActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jToggleAdoptar.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jToggleAdoptar.setForeground(new java.awt.Color(105, 211, 183));
        jToggleAdoptar.setText("ADOPTAR MASCOTAS");
        jToggleAdoptar.setPreferredSize(new java.awt.Dimension(200, 50));
        jToggleAdoptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleAdoptarActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleAdoptar);

        jToggleTienda.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jToggleTienda.setForeground(new java.awt.Color(105, 211, 183));
        jToggleTienda.setText("COMPRAR PRODUCTOS");
        jToggleTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleTiendaActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleTienda);

        jButtonHistorialMascota.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButtonHistorialMascota.setForeground(new java.awt.Color(105, 211, 183));
        jButtonHistorialMascota.setText("VER HISTORIALES MEDICOS");
        jButtonHistorialMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistorialMascotaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonHistorialMascota);

        jButtonAgendarCita.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButtonAgendarCita.setForeground(new java.awt.Color(105, 211, 183));
        jButtonAgendarCita.setText("    AGENDACION DE CITAS");
        jButtonAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarCitaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAgendarCita);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarCitaActionPerformed
        JDialogConsulta c = new JDialogConsulta(JDialogInicio.this, true, idCliente);
        c.setVisible(true);
    }//GEN-LAST:event_jButtonAgendarCitaActionPerformed

    private void jButtonHistorialMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistorialMascotaActionPerformed
        JDialogHistorial h = new JDialogHistorial(JDialogInicio.this, true, idCliente);
        h.setVisible(true);
    }//GEN-LAST:event_jButtonHistorialMascotaActionPerformed

    private void jButtonPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPanelActionPerformed
        JDialogPanel p = new JDialogPanel(JDialogInicio.this, true, usuario, contrasena);
        p.setVisible(true);
    }//GEN-LAST:event_jButtonPanelActionPerformed

    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jToggleAdoptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleAdoptarActionPerformed
        JDialogAdopciones a = new JDialogAdopciones(JDialogInicio.this, true, usuario, contrasena);
        a.setVisible(true);
    }//GEN-LAST:event_jToggleAdoptarActionPerformed

    private void jToggleTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleTiendaActionPerformed
        JDialogTienda t = new JDialogTienda(JDialogInicio.this, true, idCliente);
        t.setVisible(true);
    }//GEN-LAST:event_jToggleTiendaActionPerformed

    private void ajustarImagenLogo() {
        try {
            javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
                getClass().getResource("/recursos/logoVeterinaria.png")
            );
            java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
            logo.setIcon(new javax.swing.ImageIcon(imagenEscalada));
        } catch (Exception e) {
            System.err.println("Error al cargar logo: " + e.getMessage());
        }
    }
    private void ajustarImagenSalida() {
        try {
            javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
                getClass().getResource("/recursos/salida.png")
            );
            java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
            jButtonSalida.setIcon(new javax.swing.ImageIcon(imagenEscalada));
        } catch (Exception e) {
            System.err.println("Error al cargar imagen de salida: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogInicio dialog = new JDialogInicio(new javax.swing.JFrame(), true, "", "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendarCita;
    private javax.swing.JButton jButtonHistorialMascota;
    private javax.swing.JToggleButton jButtonPanel;
    private javax.swing.JToggleButton jButtonSalida;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleAdoptar;
    private javax.swing.JToggleButton jToggleTienda;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
