/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
/**
 *
 * @author DAM2Alu13
 */
public class JDialogConsulta extends javax.swing.JDialog {
    private String idCliente;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogConsulta.class.getName());

    /**
     * Creates new form Consulta
     */
    public JDialogConsulta(java.awt.Dialog parent, boolean modal, String idCliente) {
        super(parent, modal);
        initComponents();
        this.idCliente = idCliente;
        ajustarImagenLogo();
        configurarSpinnerHora();
        configurarDateChooser();
    }
    
     private void ajustarImagenLogo() {
    // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        logo.setIcon(iconoEscalado);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel1dia = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabeltiempo = new javax.swing.JLabel();
        jSpinnerhora = new javax.swing.JSpinner();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldid_cliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldid_mascota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(4, 4, 10, 10));

        jLabelTipo.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(105, 211, 183));
        jLabelTipo.setText("Tipo");
        jPanel2.add(jLabelTipo);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Revisión", "Vacunación", "Esterilización/Castración", "Enfermedad", "Desparasitación", "Odontología", "Cirugía", "Otros" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxTipo);

        jLabel1dia.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1dia.setForeground(new java.awt.Color(105, 211, 183));
        jLabel1dia.setText("Seleccionar dia");
        jPanel2.add(jLabel1dia);
        jPanel2.add(jDateChooser1);

        jLabelPrecio.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(105, 211, 183));
        jLabelPrecio.setText("Precio");
        jPanel2.add(jLabelPrecio);

        jTextFieldPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecio.setText("22.0");
        jTextFieldPrecio.setEnabled(false);
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPrecio);

        jLabeltiempo.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabeltiempo.setForeground(new java.awt.Color(105, 211, 183));
        jLabeltiempo.setText("Seleccionar hora");
        jPanel2.add(jLabeltiempo);
        jPanel2.add(jSpinnerhora);

        jLabelDNI.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelDNI.setForeground(new java.awt.Color(105, 211, 183));
        jLabelDNI.setText("DNI del cliente");
        jPanel2.add(jLabelDNI);
        jPanel2.add(jTextFieldid_cliente);
        jPanel2.add(jLabel11);
        jPanel2.add(jLabel8);

        jLabelID.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(105, 211, 183));
        jLabelID.setText("ID de la mascota");
        jPanel2.add(jLabelID);
        jPanel2.add(jTextFieldid_mascota);
        jPanel2.add(jLabel7);
        jPanel2.add(jLabel6);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(105, 211, 183));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REGISTRAR CITA");

        jButtonSalir.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 153, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonSiguiente.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonSiguiente.setForeground(new java.awt.Color(255, 153, 0));
        jButtonSiguiente.setText("Reservar");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSiguiente)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonSiguiente))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
    Double precio = Double.parseDouble(jTextFieldPrecio.getText());
    String id_cliente = jTextFieldid_cliente.getText().trim(); // puede estar vacío
    
    // Validar mascota
    if (jTextFieldid_mascota.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Por favor inserte el id de la mascota", 
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    int id_mascota = Integer.parseInt(jTextFieldid_mascota.getText());
    
    // Validar fecha y hora
    java.util.Date fecha = jDateChooser1.getDate();
    Object horaObj = jSpinnerhora.getValue();
    
    if (fecha == null || horaObj == null) {
        JOptionPane.showMessageDialog(this, 
            "Por favor seleccione fecha y hora para la cita", 
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try (Connection con = Conexion.getConexion()) { String sqlMascota = "SELECT nombre FROM mascota WHERE id = ?";
            PreparedStatement psMascota = con.prepareStatement(sqlMascota);
            psMascota.setInt(1, id_mascota);
            ResultSet rsMascota = psMascota.executeQuery();

            if (rsMascota.next()) {
                String nombreMascota = rsMascota.getString("nombre");
                JOptionPane.showMessageDialog(this, 
                    "Mascota encontrada: " + nombreMascota + ". Procediendo con el registro.", 
                    "Mascota válida", JOptionPane.INFORMATION_MESSAGE);

                Calendar cal = Calendar.getInstance();
                cal.setTime(fecha);
                cal.set(Calendar.HOUR_OF_DAY, 0);
                cal.set(Calendar.MINUTE, 0);
                cal.set(Calendar.SECOND, 0);
                cal.set(Calendar.MILLISECOND, 0);
                java.sql.Date sqlFecha = new java.sql.Date(cal.getTimeInMillis());

                java.sql.Time sqlHora;
                if (horaObj instanceof java.util.Date) {
                    sqlHora = new java.sql.Time(((java.util.Date) horaObj).getTime());
                } else if (horaObj instanceof String) {
                    String h = (String) jSpinnerhora.getValue(); 
                    if (h.length() == 5) { 
                        h = h + ":00";     
                    }
                    sqlHora = java.sql.Time.valueOf(h);
                } else {
                    JOptionPane.showMessageDialog(this, "Formato de hora no válido", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                String sqlVerificarCita = "SELECT COUNT(*) FROM reserva WHERE fecha = ? AND hora = ?";
                PreparedStatement psVerificar = con.prepareStatement(sqlVerificarCita);
                psVerificar.setDate(1, sqlFecha);
                psVerificar.setTime(2, sqlHora);
                ResultSet rsVerificar = psVerificar.executeQuery();
                rsVerificar.next();
                int existeCita = rsVerificar.getInt(1);

                if (existeCita > 0) {
                    JOptionPane.showMessageDialog(this, 
                        "Ya existe una cita en esa fecha y hora (" + sqlFecha + " a las " + sqlHora + ").\n" +
                        "Por favor, seleccione otra fecha u hora.", "Horario no disponible", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                String sqlInsert = "INSERT INTO consulta (tipo, precio, id_dueno, id_mascota) VALUES (?, ?, ?, ?)";
                PreparedStatement psInsert = con.prepareStatement(sqlInsert, Statement.RETURN_GENERATED_KEYS);
                psInsert.setString(1, (String) jComboBoxTipo.getSelectedItem());
                psInsert.setDouble(2, precio);

                if (id_cliente.isEmpty()) {
                    psInsert.setNull(3, java.sql.Types.VARCHAR);
                } else {
                    psInsert.setString(3, id_cliente);
                }

                psInsert.setInt(4, id_mascota);

                int filas = psInsert.executeUpdate();
                if (filas > 0) {
                    ResultSet rs = psInsert.getGeneratedKeys();
                    int IdGenerado = -1;
                    if (rs.next()) {
                        IdGenerado = rs.getInt(1);
                    }

                    String sqlReserva = "INSERT INTO reserva (id_dueno, id_consulta, fecha, hora) VALUES (?, ?, ?, ?)";
                    PreparedStatement psReserva = con.prepareStatement(sqlReserva);

                    if (id_cliente.isEmpty()) {
                        psReserva.setNull(1, java.sql.Types.VARCHAR);
                    } else {
                        psReserva.setString(1, id_cliente);
                    }
                    psReserva.setInt(2, IdGenerado);
                    psReserva.setDate(3, sqlFecha);
                    psReserva.setTime(4, sqlHora);

                    int filasReserva = psReserva.executeUpdate();
                    if (filasReserva > 0) {
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                        String fechaFormateada = sdf.format(sqlFecha);
                        JOptionPane.showMessageDialog(this, 
                            "Cita reservada correctamente para el " + fechaFormateada + " a las " + sqlHora + "\n" +
                            "ID de consulta: " + IdGenerado,  "Cita confirmada",  JOptionPane.INFORMATION_MESSAGE);

                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "La consulta se guardó pero hubo un problema al reservar la cita.",  "Advertencia", JOptionPane.WARNING_MESSAGE);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Datos incorrectos. La mascota con ID " + id_mascota + " no existe.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(this, "Ocurrió un error al validar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }       
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

        List<String> horas;
    private void configurarSpinnerHora() {
        horas = new ArrayList<>();
        for (int h = 9; h <= 20; h++) {
            horas.add(String.format("%02d:00", h));
            horas.add(String.format("%02d:30", h));
        }
        javax.swing.SpinnerListModel modeloHora = new javax.swing.SpinnerListModel(horas);
        jSpinnerhora.setModel(modeloHora);
        JSpinner.DefaultEditor editorHora = new JSpinner.DefaultEditor(jSpinnerhora);
        jSpinnerhora.setEditor(editorHora);
        jSpinnerhora.setEnabled(false);
    }

   private void configurarDateChooser() {
        jDateChooser1.addPropertyChangeListener("date", e -> {
            if (jDateChooser1.getDate() != null) {
                jSpinnerhora.setEnabled(true);

                if (!(jSpinnerhora.getModel() instanceof javax.swing.SpinnerListModel)) {
                    jSpinnerhora.setModel(new javax.swing.SpinnerListModel(horas));
                }
                jSpinnerhora.setValue(horas.get(0));
            } else {
                jSpinnerhora.setEnabled(false);
            }
        });
    }
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        String tipo =(String )jComboBoxTipo.getSelectedItem();
        double precio=0.0;
        
        switch(tipo){
            case"Revisión":
                precio=22;
                break;//Revisión, Vacunación, Esterilización /Castración, Enfermedad, Desparasitación, Odontología, Cirugía, Otros
            case"Vacunación":
                precio=25;
                break;
            case"Esterilización/Castración":
                precio=100;
                break;
            case"Enfermedad":
                precio=30;
                break;
            case"Desparasitación":
                precio=20;
                break;
            case"Odontología":
                precio=85;
                break;
            case"Cirugía":
                precio=1200;
                break;
            case"Otros":
                jTextFieldPrecio.setText("El costo sera determinado por el especialista");
                return;
        }
        jTextFieldPrecio.setText(String.valueOf(precio));
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogConsulta dialog = new JDialogConsulta(new javax.swing.JDialog(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1dia;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabeltiempo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerhora;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldid_cliente;
    private javax.swing.JTextField jTextFieldid_mascota;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}