/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import java.sql.*;

import java.util.List;

import java.util.ArrayList;


/**
 *
 * @author DAM2Alu13
 */
public class JDialogCitas extends javax.swing.JDialog { 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogCitas.class.getName());
   
    /**
     * Creates new form Citas
     */
    private static final Set<String> reservas = new HashSet<>();
    String id_cliente ;
    public JDialogCitas(java.awt.Dialog parent, boolean modal, String idCliente) {
        super(parent, modal);
        this.id_cliente = idCliente;
        initComponents();
        ajustarImagenLogo();
        configurarSpinnerHora();
        configurarDateChooser();
    }
    
   
    List<String> horas;
    private void configurarSpinnerHora() {
        horas = new ArrayList<>();
        for (int h = 9; h <= 20; h++) {
            horas.add(String.format("%02d:00", h));
            horas.add(String.format("%02d:30", h));
        }
        javax.swing.SpinnerListModel modeloHora = new javax.swing.SpinnerListModel(horas);
        jSpinnerhora.setModel(modeloHora);
        JSpinner.DefaultEditor editorHora = new JSpinner.DefaultEditor(jSpinnerhora);
        jSpinnerhora.setEditor(editorHora);
        jSpinnerhora.setEnabled(false);
    }

   private void configurarDateChooser() {
    jDateChooser1.addPropertyChangeListener("date", e -> {
        if (jDateChooser1.getDate() != null) {
            jSpinnerhora.setEnabled(true);
           
            if (!(jSpinnerhora.getModel() instanceof javax.swing.SpinnerListModel)) {
                jSpinnerhora.setModel(new javax.swing.SpinnerListModel(horas));
            }
            jSpinnerhora.setValue(horas.get(0));
        } else {
            jSpinnerhora.setEnabled(false);
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jButtonReserva = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jSpinnerhora = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N

        jButtonReserva.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonReserva.setForeground(new java.awt.Color(255, 153, 0));
        jButtonReserva.setText("Reservar");
        jButtonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservaActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 153, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(105, 211, 183));
        jLabel5.setText("Reserva ya tu cita");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReserva)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSpinnerhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReserva)
                    .addComponent(jButtonSalir))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservaActionPerformed
     Date fecha = jDateChooser1.getDate();
    Object horaObj = jSpinnerhora.getValue();

    if (fecha == null || horaObj == null) {
        JOptionPane.showMessageDialog(this, "Seleccione fecha y hora", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Normaliza fecha a medianoche
    Calendar cal = Calendar.getInstance();
    cal.setTime(fecha);
    cal.set(Calendar.HOUR_OF_DAY, 0);
    cal.set(Calendar.MINUTE, 0);
    cal.set(Calendar.SECOND, 0);
    cal.set(Calendar.MILLISECOND, 0);
    java.sql.Date sqlFecha = new java.sql.Date(cal.getTimeInMillis());

    // Convierte hora según modelo del spinner
    java.sql.Time sqlHora;
    if (horaObj instanceof Date) {
        sqlHora = new java.sql.Time(((Date) horaObj).getTime());
    } else if (horaObj instanceof String) {
       
       String h = (String) jSpinnerhora.getValue(); 
    if (h.length() == 5) { 
        h = h + ":00";     
        }
     sqlHora = java.sql.Time.valueOf(h);
    }
    else {
    JOptionPane.showMessageDialog(this, "Formato de hora no válido", "Error", JOptionPane.ERROR_MESSAGE);
    return;
    }
    try (Connection conn = Conexion.getConexion()) {
        conn.setAutoCommit(true);
        String sqlReserva = "INSERT INTO reserva (id_cliente, fecha, hora) VALUES (?, ?, ?, ?)";

        try (PreparedStatement ps = conn.prepareStatement(sqlReserva)) {
            if (id_cliente == null || id_cliente.isEmpty()) {
                ps.setNull(1, java.sql.Types.VARCHAR);
            } else {
                ps.setString(1, id_cliente);
            }
            ps.setDate(2, sqlFecha);
            ps.setTime(3, sqlHora);

            int filas = ps.executeUpdate();
            if (filas == 0) {
                JOptionPane.showMessageDialog(this, "No se insertó la reserva", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Cita reservada en BD para " + sqlFecha + " " + sqlHora, "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    } catch (SQLException ex) {
        ex.printStackTrace(); // para ver el detalle
        JOptionPane.showMessageDialog(this, "Error al guardar cita: " + ex.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
    }
    
        
        String clave = cal.getTime() + " " + sqlHora;

        if (reservas.contains(clave)) {
            JOptionPane.showMessageDialog(this, "Ya existe una cita en esa hora", "Ocupado", JOptionPane.WARNING_MESSAGE);
        } else {
            reservas.add(clave);
            JOptionPane.showMessageDialog(this, "Cita reservada para " + clave, "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        }
              
    }//GEN-LAST:event_jButtonReservaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed
     private void ajustarImagenLogo() {
    // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        logo.setIcon(iconoEscalado);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
      
            public void run() {
                JDialogCitas dialog = new JDialogCitas(new javax.swing.JDialog(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReserva;
    private javax.swing.JButton jButtonSalir;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerhora;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
