/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;

import Veterinaria.Conexion;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
;
/**
 *
 * @author DAM2Alu13
 */
public class JDialogTableVeterinarios extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogTableVeterinarios.class.getName());
    private TableRowSorter<TableModel> order;

    /**
     * Creates new form JDialogTableVeterinarios
     */
    public JDialogTableVeterinarios(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ajustarImagenLogo(); 
        cargarUsuariosEnTabla();
        order = new TableRowSorter<>(jTableVeterinarios.getModel());
        jTableVeterinarios.setRowSorter(order);

    }
    
   private void cargarUsuariosEnTabla() {
    
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[][] {},
        new String[] { "ID", "Nombre", "Apellidos", "Teléfono", "Correo", "Usuario" }
    ) {
        
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };

    String sql = "SELECT id, nombre, apellidos, telefono, correo, usuario FROM usuario WHERE rol = 'Veterinario'";

    try (Connection con = Conexion.getConexion();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(sql)) {

        while (rs.next()) {
            Object[] fila = new Object[7];
            fila[0] = rs.getString("id");
            fila[1] = rs.getString("nombre");
            fila[2] = rs.getString("apellidos");
            fila[3] = rs.getString("telefono");
            fila[4] = rs.getString("correo");
            fila[5] = rs.getString("usuario");
            

            modelo.addRow(fila);
        }

        jTableVeterinarios.setModel(modelo);
        jTableVeterinarios.setDefaultEditor(Object.class, null); // Refuerzo: desactiva edición

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
} 

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jLabelBuscarDNI = new javax.swing.JLabel();
        jTextFieldBuscaDNI = new javax.swing.JTextField();
        jLabelBuscarNombre = new javax.swing.JLabel();
        jTextFieldBuscanombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeterinarios = new javax.swing.JTable();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jButtonSalir.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(133, 210, 204));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir);

        jButtonInsertar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonInsertar.setForeground(new java.awt.Color(255, 153, 0));
        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInsertar);

        jButtonBorrar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonBorrar.setForeground(new java.awt.Color(133, 210, 204));
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBorrar);

        jLabelBuscarDNI.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabelBuscarDNI.setForeground(new java.awt.Color(52, 164, 175));
        jLabelBuscarDNI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBuscarDNI.setText("Buscar por DNI:");
        jPanel1.add(jLabelBuscarDNI);

        jTextFieldBuscaDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaDNIActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBuscaDNI);

        jLabelBuscarNombre.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabelBuscarNombre.setForeground(new java.awt.Color(52, 164, 175));
        jLabelBuscarNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBuscarNombre.setText("Buscar por nombre:");
        jPanel1.add(jLabelBuscarNombre);

        jTextFieldBuscanombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscanombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBuscanombre);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableVeterinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellidos", "Telefono", "Correo", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVeterinarios);
        if (jTableVeterinarios.getColumnModel().getColumnCount() > 0) {
            jTableVeterinarios.getColumnModel().getColumn(0).setMinWidth(12);
            jTableVeterinarios.getColumnModel().getColumn(0).setPreferredWidth(12);
            jTableVeterinarios.getColumnModel().getColumn(1).setMinWidth(30);
            jTableVeterinarios.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTableVeterinarios.getColumnModel().getColumn(2).setMinWidth(40);
            jTableVeterinarios.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTableVeterinarios.getColumnModel().getColumn(3).setMinWidth(20);
            jTableVeterinarios.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        JDialogpanelinsertarvet jpi = new JDialogpanelinsertarvet(JDialogTableVeterinarios.this, true);
        jpi.setVisible(true);
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        
        JDialogpanelBorrarvet jdb = new JDialogpanelBorrarvet(JDialogTableVeterinarios.this, true);
        jdb.setVisible(true);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldBuscaDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaDNIActionPerformed
         try {
        RowFilter<Object, Object> rf = RowFilter.regexFilter(
            "^" + jTextFieldBuscaDNI.getText(),  
            0                                    
        );
        order.setRowFilter(rf);
    } catch (Exception pse) {
        System.out.println("Ha ocurrido un error");
    } 
    }//GEN-LAST:event_jTextFieldBuscaDNIActionPerformed

    private void jTextFieldBuscanombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscanombreActionPerformed
        try {
        RowFilter<Object, Object> rf = RowFilter.regexFilter(
            "^" + jTextFieldBuscanombre.getText(),  
            1                                    
        );
        order.setRowFilter(rf);
    } catch (Exception pse) {
        System.out.println("Ha ocurrido un error");
    } 
    }//GEN-LAST:event_jTextFieldBuscanombreActionPerformed

    private void ajustarImagenLogo() {
    // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        logo.setIcon(iconoEscalado);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogTableVeterinarios dialog = new JDialogTableVeterinarios(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBuscarDNI;
    private javax.swing.JLabel jLabelBuscarNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeterinarios;
    private javax.swing.JTextField jTextFieldBuscaDNI;
    private javax.swing.JTextField jTextFieldBuscanombre;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
