/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author julia
 */
public class JDialogHistorial extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogHistorial.class.getName());
    private String id_dueno;
    /**
     * Creates new form JDialogHistorial
     */
    public JDialogHistorial(java.awt.Dialog parent, boolean modal, String dueno) {
        super(parent, modal);
        this.id_dueno=dueno;
        initComponents();
        ajustarImagenLogo();
        cargarHistorialMascotas();
    }
    
     private void cargarHistorialMascotas() {
        // Definimos un modelo no editable
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][]{},
            new String[]{
                "ID", "Nombre", "Especie", "Edad", "Sexo", "Peso", "Vacunas", "Historial"
            }
        ) {
            Class[] types = new Class[]{
                Integer.class, String.class, String.class, String.class,
                String.class, Double.class, Boolean.class, String.class
            };

            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        jTablehistorial.setModel(modelo);

        String sql = "SELECT id, nombre, especie, edad, sexo, peso, vacunas, historial FROM mascota WHERE id_dueno = ?";

        try (Connection conn = Conexion.getConexion();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, id_dueno);

            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String nombre = rs.getString("nombre");
                String especie = rs.getString("especie");
                String edad = rs.getString("edad");
                String sexo = rs.getString("sexo");
                double peso = rs.getDouble("peso");
                boolean vacunas = rs.getInt("vacunas") == 1;
                String historial = rs.getString("historial");

                modelo.addRow(new Object[]{id, nombre, especie, edad, sexo, peso, vacunas, historial});
            }

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar historial", ex);
            JOptionPane.showMessageDialog(this, "No se pudo cargar el historial.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablehistorial = new javax.swing.JTable();
        jButtonatras = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTablehistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Especie", "Edad", "Sexo", "Peso", "Vacunas", "Historial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablehistorial);
        if (jTablehistorial.getColumnModel().getColumnCount() > 0) {
            jTablehistorial.getColumnModel().getColumn(0).setMinWidth(10);
            jTablehistorial.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTablehistorial.getColumnModel().getColumn(1).setMinWidth(30);
            jTablehistorial.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTablehistorial.getColumnModel().getColumn(2).setMinWidth(40);
            jTablehistorial.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTablehistorial.getColumnModel().getColumn(3).setMinWidth(10);
            jTablehistorial.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTablehistorial.getColumnModel().getColumn(4).setMinWidth(15);
            jTablehistorial.getColumnModel().getColumn(4).setPreferredWidth(15);
            jTablehistorial.getColumnModel().getColumn(5).setMinWidth(10);
            jTablehistorial.getColumnModel().getColumn(5).setPreferredWidth(10);
            jTablehistorial.getColumnModel().getColumn(6).setMinWidth(10);
            jTablehistorial.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        jButtonatras.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonatras.setForeground(new java.awt.Color(133, 210, 204));
        jButtonatras.setText("Atras");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(60, 60));
        logo.setMinimumSize(new java.awt.Dimension(60, 60));
        logo.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonatras)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonatras)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void ajustarImagenLogo() {
        // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        logo.setIcon(iconoEscalado);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogHistorial dialog = new JDialogHistorial(new javax.swing.JDialog(), true,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonatras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablehistorial;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
