/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;

import javax.swing.JOptionPane;

/**
 *
 * @author julia
 */
public class JDialogpanelAdministrador extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogpanelAdministrador.class.getName());

    /**
     * Creates new form JDialogpanelAdministrador
     */
    public JDialogpanelAdministrador(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ajustarImagenLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabelBienvenida = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtoninsertarvet = new javax.swing.JButton();
        jButtonusuarios = new javax.swing.JButton();
        jButtoninsertarproductos = new javax.swing.JButton();
        jButtonconmascotas = new javax.swing.JButton();
        jButtonconsultacompras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N

        jLabelBienvenida.setFont(new java.awt.Font("Candara", 2, 18)); // NOI18N
        jLabelBienvenida.setForeground(new java.awt.Color(133, 210, 204));
        jLabelBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBienvenida.setText("Panel de Administrador");

        jPanel2.setLayout(new java.awt.GridLayout(2, 7, 10, 10));

        jLabel1.setText("veterinarios");
        jPanel2.add(jLabel1);

        jLabel2.setText("consultar");
        jPanel2.add(jLabel2);

        jLabel3.setText("producto");
        jPanel2.add(jLabel3);

        jLabel4.setText("mascotas");
        jPanel2.add(jLabel4);

        jLabel5.setText("compras");
        jPanel2.add(jLabel5);

        jButtoninsertarvet.setForeground(new java.awt.Color(255, 153, 0));
        jButtoninsertarvet.setText("administrar ");
        jButtoninsertarvet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninsertarvetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtoninsertarvet);

        jButtonusuarios.setForeground(new java.awt.Color(255, 153, 0));
        jButtonusuarios.setText("consulta usuarios");
        jButtonusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonusuariosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonusuarios);

        jButtoninsertarproductos.setForeground(new java.awt.Color(255, 153, 0));
        jButtoninsertarproductos.setText("insertar productos");
        jButtoninsertarproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninsertarproductosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtoninsertarproductos);

        jButtonconmascotas.setForeground(new java.awt.Color(255, 153, 0));
        jButtonconmascotas.setText("consulta mascotas");
        jButtonconmascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconmascotasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonconmascotas);

        jButtonconsultacompras.setForeground(new java.awt.Color(255, 153, 0));
        jButtonconsultacompras.setText("consulta compras ");
        jButtonconsultacompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconsultacomprasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonconsultacompras);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 209, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoninsertarvetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninsertarvetActionPerformed
     //   JDialogpanelinsertarvet jpv = new JDialogpanelinsertarvet(JDialogpanelAdministrador.this, true);
     //   jpv.setVisible(true);
          JDialogTableVeterinarios jpv = new JDialogTableVeterinarios(JDialogpanelAdministrador.this, true);
          jpv.setVisible(true);
    }//GEN-LAST:event_jButtoninsertarvetActionPerformed

    private void jButtoninsertarproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninsertarproductosActionPerformed
        String[] opciones = {"Manual", "Importar JSON/XML", "Cancelar"};

        int eleccion = JOptionPane.showOptionDialog(this, "Elige el método de inserción", "Insertar Veterinario", 
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0] );

        if (eleccion == 0) {
            JDialoginsertarProductos jdp= new JDialoginsertarProductos(JDialogpanelAdministrador.this, true);
            jdp.setVisible(true);

        } else if (eleccion == 1) {

        }
    }//GEN-LAST:event_jButtoninsertarproductosActionPerformed

    private void jButtonusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonusuariosActionPerformed
        JDialogconsultausuarios jp= new JDialogconsultausuarios(JDialogpanelAdministrador.this, true);
        jp.setVisible(true);
    }//GEN-LAST:event_jButtonusuariosActionPerformed

    private void jButtonconmascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconmascotasActionPerformed
        JDialogconsultamascotas jp = new JDialogconsultamascotas(JDialogpanelAdministrador.this, true);
        jp.setVisible(true);
    }//GEN-LAST:event_jButtonconmascotasActionPerformed

    private void jButtonconsultacomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconsultacomprasActionPerformed
        JDialogconsultacompras jp =new JDialogconsultacompras(JDialogpanelAdministrador.this, true);
        jp.setVisible(true);
    }//GEN-LAST:event_jButtonconsultacomprasActionPerformed
    
     private void ajustarImagenLogo() {
    // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        logo.setIcon(iconoEscalado);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogpanelAdministrador dialog = new JDialogpanelAdministrador(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonconmascotas;
    private javax.swing.JButton jButtonconsultacompras;
    private javax.swing.JButton jButtoninsertarproductos;
    private javax.swing.JButton jButtoninsertarvet;
    private javax.swing.JButton jButtonusuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
