/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DAM2Alu2
 */
public class JDialogAltaMascota extends javax.swing.JDialog {
    private JDialogVeterinarioMascotas padre;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAltaMascota.class.getName());

    /**
     * Creates new form JDialogAltaMascota
     */
    public JDialogAltaMascota(JDialogVeterinarioMascotas parent, boolean modal) {
        super(parent, modal);
        this.padre = parent;
        initComponents();
        ajustarImagenLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 10, 0));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 164, 175));
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1);

        jTextField1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(105, 211, 183));
        jPanel1.add(jTextField1);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 164, 175));
        jLabel2.setText("Especie y Raza");
        jPanel1.add(jLabel2);

        jTextField2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(105, 211, 183));
        jPanel1.add(jTextField2);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 164, 175));
        jLabel3.setText("Edad");
        jPanel1.add(jLabel3);

        jTextField3.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(105, 211, 183));
        jPanel1.add(jTextField3);

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 164, 175));
        jLabel4.setText("Sexo");
        jPanel1.add(jLabel4);

        jTextField4.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(105, 211, 183));
        jPanel1.add(jTextField4);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 164, 175));
        jLabel5.setText("Peso");
        jPanel1.add(jLabel5);

        jTextField5.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(105, 211, 183));
        jPanel1.add(jTextField5);

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 164, 175));
        jLabel6.setText("Vacunas");
        jPanel1.add(jLabel6);

        jTextField6.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(105, 211, 183));
        jPanel1.add(jTextField6);

        jLabel7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 164, 175));
        jLabel7.setText("Historial");
        jPanel1.add(jLabel7);

        jTextField7.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(105, 211, 183));
        jPanel1.add(jTextField7);

        jLabel10.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(52, 164, 175));
        jLabel10.setText("DNI del dueño");
        jPanel1.add(jLabel10);

        jTextField8.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(105, 211, 183));
        jPanel1.add(jTextField8);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jPanel2.add(jLabel8);

        jButton1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Guardar Cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(133, 210, 204));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jPanel2.add(jLabel9);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(60, 60));
        logo.setMinimumSize(new java.awt.Dimension(60, 60));
        logo.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try (Connection con = Conexion.getConexion()) {
            String sql = "INSERT INTO mascota (nombre, especie, edad, sexo, peso, vacunas, historial, id_dueno) "
                       + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, jTextField1.getText());
            ps.setString(2, jTextField2.getText());
            ps.setString(3, jTextField3.getText());
            ps.setString(4, jTextField4.getText());
            ps.setDouble(5, Double.parseDouble(jTextField5.getText()));
            ps.setBoolean(6, Boolean.parseBoolean(jTextField6.getText()));
            ps.setString(7, jTextField7.getText());

            // id_dueno puede ser null
            if (jTextField8.getText().trim().isEmpty()) {
                ps.setString(8, null);
            } else {
                ps.setString(8, jTextField8.getText());
            }

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Mascota añadida correctamente.");
            if (padre != null) {
                padre.cargarTablaMascotas();
            }
            this.dispose();

        } catch (SQLException ex) {
            // Captura violación de FK
            if (ex.getMessage().toLowerCase().contains("foreign key")) {
                JOptionPane.showMessageDialog(this,
                    "Error: el DNI del dueño no existe.",
                    "Error FK",
                    JOptionPane.ERROR_MESSAGE);
            } else {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,
                    "Error al añadir mascota: " + ex.getMessage(),
                    "Error BD",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ajustarImagenLogo() {
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);
        logo.setIcon(iconoEscalado);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
