/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.w3c.dom.NodeList;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import javax.xml.parsers.DocumentBuilderFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
/**
 *
 * @author Administrador
 */
public class JDialogInsercionDatos extends javax.swing.JDialog {

    /**
     * Creates new form JDialogInsercionDatos
     */
    private File archivoSeleccionado = null;
    public JDialogInsercionDatos(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ajustarImagenLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonSeleccionar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonArchivo = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldNombre.setEnabled(false);
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(64, 25));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jButtonSeleccionar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonSeleccionar.setForeground(new java.awt.Color(255, 153, 0));
        jButtonSeleccionar.setText("Seleccionar");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSeleccionar);

        jButtonCancelar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(105, 211, 183));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar);

        jButtonArchivo.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonArchivo.setForeground(new java.awt.Color(52, 164, 175));
        jButtonArchivo.setText("Archivo");
        jButtonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArchivoActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(60, 60));
        logo.setMinimumSize(new java.awt.Dimension(60, 60));
        logo.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonArchivo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArchivoActionPerformed
        if (archivoSeleccionado != null) {
            archivoSeleccionado = null;
            jTextFieldNombre.setText("");
            return;
        }

        JFileChooser fileChooser = new JFileChooser();

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos JSON o XML", "json", "xml");
        fileChooser.setFileFilter(filtro);

        int elegirArchivo = fileChooser.showOpenDialog(this);
        if (elegirArchivo == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String nombre = archivo.getName().toLowerCase();

            if (nombre.endsWith(".json") || nombre.endsWith(".xml")) {
                archivoSeleccionado = archivo;
                jTextFieldNombre.setText(archivo.getName());
            } else {
                JOptionPane.showMessageDialog(this, "Formato no válido");
            }
        }
    }//GEN-LAST:event_jButtonArchivoActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        if (archivoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un archivo primero");
            return;
        }

        String nombre = archivoSeleccionado.getName().toLowerCase();

        try {
            if (nombre.endsWith(".json")) {
                archivoJson(archivoSeleccionado);
            } else if (nombre.endsWith(".xml")) {
                archivoXML(archivoSeleccionado);
            } else {
                JOptionPane.showMessageDialog(this, "Formato no soportado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar archivo: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private boolean insertarProducto(String nombre, String descripcion, String tipo, double precio, int unidades) {
        String sql = "INSERT INTO producto (nombre, descripcion, tipo, precio, unidades) VALUES (?, ?, ?, ?, ?)";
        
        try (Connection con = Conexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, nombre);
            ps.setString(2, descripcion);
            ps.setString(3, tipo);
            ps.setDouble(4, precio);
            ps.setInt(5, unidades);

            int resultado = ps.executeUpdate();
            return resultado > 0;
            
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Error al insertar producto '" + nombre + "': " + e.getMessage(),
                "Error BD", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private void archivoXML(File archivo) throws Exception {
        Document doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(archivo);
        doc.getDocumentElement().normalize();

        NodeList lista = doc.getElementsByTagName("*");
        if (lista.getLength() == 0) {
            throw new Exception("XML vacío");
        }
        Element primerElemento = (Element) lista.item(0);
        if (primerElemento.getElementsByTagName("nombre").getLength() > 0) {
            NodeList productos = doc.getElementsByTagName("producto");
            for (int i = 0; i < productos.getLength(); i++) {
                Element e = (Element) productos.item(i);

                String nombre = e.getElementsByTagName("nombre").item(0).getTextContent();
                String descripcion = e.getElementsByTagName("descripcion").item(0).getTextContent();
                String tipo = e.getElementsByTagName("tipo").item(0).getTextContent();
                double precio = Double.parseDouble(e.getElementsByTagName("precio").item(0).getTextContent());
                int unidades = Integer.parseInt(e.getElementsByTagName("unidades").item(0).getTextContent());

                insertarProducto(nombre, descripcion, tipo, precio, unidades);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Formato XML no reconocido");
        }

        JOptionPane.showMessageDialog(this, "Datos importados correctamente");
    }
    private void archivoJson(File archivo) throws Exception {
        Gson gson = new Gson();
    
    JsonArray array = JsonParser.parseReader(new FileReader(archivo)).getAsJsonArray();
    
    if (array.size() == 0) {
        throw new Exception("Archivo vacío");
    }
    
    JsonObject obj = array.get(0).getAsJsonObject();
    
    if (obj.has("nombre")) {
        for (int i = 0; i < array.size(); i++) {
            JsonObject productoObj = array.get(i).getAsJsonObject();
            
            String nombre = productoObj.get("nombre").getAsString();
            String descripcion = productoObj.get("descripcion").getAsString();
            String tipo = productoObj.get("tipo").getAsString();
            double precio = productoObj.get("precio").getAsDouble();
            int unidades = productoObj.get("unidades").getAsInt();
            
            insertarProducto(nombre, descripcion, tipo, precio, unidades);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Formato JSON no reconocido");
    }
    
    JOptionPane.showMessageDialog(this, "Datos importados correctamente");
    }
    
    private void insertarUsuario(Usuario u) {
        String sql = "INSERT INTO usuario (id, nombre, apellidos, telefono, correo, usuario, rol) VALUES (?, ?, ?, ?, ?, ?, ?)";
        try (Connection con = Conexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, u.getId());
            ps.setString(2, u.getNombre());
            ps.setString(3, u.getApellidos());
            ps.setString(4, u.getTelefono());
            ps.setString(5, u.getCorreo());
            ps.setString(6, u.getUsuario());
            ps.setString(7, u.getRol());

            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al insertar usuario: " + e.getMessage());
        }
    }
    
    private void insertarMascota(Mascota m) {
        String sql = "INSERT INTO mascota (nombre, especie, edad, sexo, peso, vacunas, historial, id_dueno) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection con = Conexion.getConexion(); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, m.getNombre());
            ps.setString(2, m.getEspecie());
            ps.setString(3, m.getEdad());
            ps.setString(4, m.getSexo());
            ps.setDouble(5, m.getPeso());
            ps.setBoolean(6, m.isVacunas());
            ps.setString(7, m.getHistorial());
            ps.setString(8, m.getIdDueno());

            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al insertar mascota: " + e.getMessage());
        }
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void ajustarImagenLogo() {
        // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        logo.setIcon(iconoEscalado);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogInsercionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogInsercionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogInsercionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogInsercionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogInsercionDatos dialog = new JDialogInsercionDatos(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArchivo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
