/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;
import java.sql.*;
/**
 *
 * @author DAM2Alu13
 */
public class JDialogConsulta extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogConsulta.class.getName());

    /**
     * Creates new form Consulta
     */
    public JDialogConsulta(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ajustarImagenLogo();
    }
    
     private void ajustarImagenLogo() {
    // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        logo.setIcon(iconoEscalado);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldid_cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldid_mascota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoVeterinaria.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 211, 183));
        jLabel1.setText("Tipo");
        jPanel2.add(jLabel1);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Revisión", "Vacunación", "Esterilización/Castración", "Enfermedad", "Desparasitación", "Odontología", "Cirugía", "Otros" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxTipo);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(105, 211, 183));
        jLabel2.setText("Precio");
        jPanel2.add(jLabel2);

        jTextFieldPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecio.setEnabled(false);
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPrecio);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(105, 211, 183));
        jLabel3.setText("Id cliente ");
        jPanel2.add(jLabel3);
        jPanel2.add(jTextFieldid_cliente);

        jLabel4.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(105, 211, 183));
        jLabel4.setText("id mascota");
        jPanel2.add(jLabel4);
        jPanel2.add(jTextFieldid_mascota);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(105, 211, 183));
        jLabel5.setText("REGISTRO DE LA CONSULTA");

        jButtonSalir.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 153, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonSiguiente.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonSiguiente.setForeground(new java.awt.Color(255, 153, 0));
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSiguiente)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonSiguiente))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        
    //String tipo = jTextFieldTipo.getText();
    Double precio = Double.parseDouble(jTextFieldPrecio.getText());
    String id_cliente = jTextFieldid_cliente.getText().trim(); // puede estar vacío
    int id_mascota = Integer.parseInt(jTextFieldid_mascota.getText());
    
    try (Connection con = Conexion.getConexion()) {
        
        
        String sqlMascota = "SELECT nombre FROM mascota WHERE id = ?";
        PreparedStatement psMascota = con.prepareStatement(sqlMascota);
        psMascota.setInt(1, id_mascota);
        
        ResultSet rsMascota = psMascota.executeQuery();
        
        if (rsMascota.next()) {
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Mascota encontrada: " + rsMascota.getString("nombre") + ". Podemos continuar.");
            
         
            //Citas citas = new Citas(Consulta.this,true);
            //citas.setVisible(true);
            
            jButtonSiguiente.setEnabled(true);
            
            
            String sqlInsert = "INSERT INTO consulta (tipo, precio, id_cliente, id_mascota) VALUES (?, ?, ?, ?)";
             PreparedStatement psInsert = con.prepareStatement(sqlInsert, Statement.RETURN_GENERATED_KEYS);
            psInsert.setString(1, (String) jComboBoxTipo.getSelectedItem());
            psInsert.setDouble(2, precio);
            
            if (id_cliente.isEmpty()) {
                psInsert.setNull(3, java.sql.Types.VARCHAR); // cliente opcional
            } else {
                psInsert.setString(3, id_cliente);
            }
            
            psInsert.setInt(4, id_mascota);
            
            int filas = psInsert.executeUpdate();
            if (filas > 0) {
                ResultSet rs=psInsert.getGeneratedKeys();
                int IdGenerado=-1;
                if(rs.next()){
                    IdGenerado=rs.getInt(1);
                }
                
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Consulta registrada correctamente.");
                
               
               JDialogCitas citas = new JDialogCitas(JDialogConsulta.this, true, IdGenerado, id_cliente); 
               citas.setVisible(true);

            }
            
        } else {
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Datos incorrectos. La mascota con ID " + id_mascota + " no existe.",
                "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            
            jButtonSiguiente.setEnabled(false);
        }
        
    } catch (SQLException e) {
        System.err.println(e);
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Ocurrió un error al validar los datos: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
            
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
        
       

        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        String tipo =(String )jComboBoxTipo.getSelectedItem();
        double precio=0.0;
        
        switch(tipo){
            case"Revisión":
                precio=22;
                break;//Revisión, Vacunación, Esterilización /Castración, Enfermedad, Desparasitación, Odontología, Cirugía, Otros
            case"Vacunación":
                precio=25;
                break;
            case"Esterilización/Castración":
                precio=100;
                break;
            case"Enfermedad":
                precio=30;
                break;
            case"Desparasitación":
                precio=20;
                break;
            case"Odontología":
                precio=85;
                break;
            case"Cirugía":
                precio=1200;
                break;
            case"Otros":
                jTextFieldPrecio.setText("El costo sera determinado por el especialista");
                return;
        }
        jTextFieldPrecio.setText(String.valueOf(precio));
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogConsulta dialog = new JDialogConsulta(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldid_cliente;
    private javax.swing.JTextField jTextFieldid_mascota;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
