/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.w3c.dom.NodeList;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import javax.xml.parsers.DocumentBuilderFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
/**
 *
 * @author Administrador
 */
public class JDialogInsercionDatos extends javax.swing.JDialog {

    /**
     * Creates new form JDialogInsercionDatos
     */
    public String tabla = "";
    private File archivoSeleccionado = null;
    public JDialogInsercionDatos(java.awt.Frame parent, boolean modal, String tabla) {
        super(parent, modal);
        this.tabla = tabla;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonSeleccionar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldNombre.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jButtonSeleccionar.setText("Seleccionar");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSeleccionar);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar);

        jButtonArchivo.setText("Archivo");
        jButtonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonArchivo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArchivoActionPerformed
        if (archivoSeleccionado != null) {
            archivoSeleccionado = null;
            jTextFieldNombre.setText("");
            return;
        }

        JFileChooser fileChooser = new JFileChooser();

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos JSON o XML", "json", "xml");
        fileChooser.setFileFilter(filtro);

        int elegirArchivo = fileChooser.showOpenDialog(this);
        if (elegirArchivo == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String nombre = archivo.getName().toLowerCase();

            if (nombre.endsWith(".json") || nombre.endsWith(".xml")) {
                archivoSeleccionado = archivo;
                jTextFieldNombre.setText(archivo.getName());
            } else {
                JOptionPane.showMessageDialog(this, "Formato no válido");
            }
        }
    }//GEN-LAST:event_jButtonArchivoActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        if (archivoSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Selecciona un archivo primero");
        return;
    }

    String nombre = archivoSeleccionado.getName().toLowerCase();

    try {
        if (nombre.endsWith(".json")) {
            archivoJson(archivoSeleccionado);
        } else if (nombre.endsWith(".xml")) {
            archivoXML(archivoSeleccionado);
        } else {
            JOptionPane.showMessageDialog(this, "Formato no soportado");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al procesar archivo");
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void archivoXML(File archivo) throws Exception {
        Document doc = (Document) DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(archivo);
        doc.getDocumentElement().normalize();

        NodeList lista = doc.getElementsByTagName("*");
        if (lista.getLength() == 0) {
            throw new Exception("XML vacío");
        }
        Element primerElemento = (Element) lista.item(0);
        if (primerElemento.getElementsByTagName("apellidos").getLength() > 0) {
            if (!tabla.equalsIgnoreCase("usuario")) {
                JOptionPane.showMessageDialog(this, "Error: archivo de usuarios en tabla incorrecta");
                return;
            }

            NodeList usuarios = doc.getElementsByTagName("usuario");
            for (int i = 0; i < usuarios.getLength(); i++) {
                Element e = (Element) usuarios.item(i);

                Usuario u = new Usuario();
                u.setId(e.getElementsByTagName("id").item(0).getTextContent());
                u.setNombre(e.getElementsByTagName("nombre").item(0).getTextContent());
                u.setApellidos(e.getElementsByTagName("apellidos").item(0).getTextContent());
                u.setTelefono(e.getElementsByTagName("telefono").item(0).getTextContent());
                u.setCorreo(e.getElementsByTagName("correo").item(0).getTextContent());
                u.setUsuario(e.getElementsByTagName("usuario").item(0).getTextContent());
                u.setRol(e.getElementsByTagName("rol").item(0).getTextContent());

                insertarUsuario(u);
            }

        } else if (primerElemento.getElementsByTagName("especie").getLength() > 0) {
            if (!tabla.equalsIgnoreCase("mascota")) {
                JOptionPane.showMessageDialog(this, "Error: archivo de mascotas en tabla incorrecta");
                return;
            }
            NodeList mascotas = doc.getElementsByTagName("mascota");

            for (int i = 0; i < mascotas.getLength(); i++) {
                Element e = (Element) mascotas.item(i);
                Mascota m = new Mascota();
                m.setNombre(e.getElementsByTagName("nombre").item(0).getTextContent());
                m.setEspecie(e.getElementsByTagName("especie").item(0).getTextContent());
                m.setEdad(e.getElementsByTagName("edad").item(0).getTextContent());
                m.setSexo(e.getElementsByTagName("sexo").item(0).getTextContent());
                m.setPeso(Double.parseDouble(e.getElementsByTagName("peso").item(0).getTextContent()));
                m.setVacunas(Boolean.parseBoolean(e.getElementsByTagName("vacunas").item(0).getTextContent()));
                insertarMascota(m);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Formato XML no reconocido");
        }

        JOptionPane.showMessageDialog(this, "Datos importados correctamente");
    }
    private void archivoJson(File archivo) throws Exception {
        Gson gson = new Gson();

        JsonArray array = JsonParser.parseReader(new FileReader(archivo)).getAsJsonArray();

        if (array.size() == 0) {
            throw new Exception("Archivo vacío");
        }

        JsonObject obj = array.get(0).getAsJsonObject();

        // Detectar tipo
        if (obj.has("apellidos")) {
            // 👉 USUARIO
            if (!tabla.equalsIgnoreCase("usuario")) {
                JOptionPane.showMessageDialog(this, "Error: el archivo es de USUARIOS pero la tabla actual es " + tabla);
                return;
            }

            Usuario[] usuarios = gson.fromJson(array, Usuario[].class);

            for (Usuario u : usuarios) {
                insertarUsuario(u);
            }

        } else if (obj.has("especie")) {
            if (!tabla.equalsIgnoreCase("mascota")) {
                JOptionPane.showMessageDialog(this, "Error: el archivo es de MASCOTAS pero la tabla actual es " + tabla);
                return;
            }

            Mascota[] mascotas = gson.fromJson(array, Mascota[].class);

            for (Mascota m : mascotas) {
                insertarMascota(m);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Formato JSON no reconocido");
        }

        JOptionPane.showMessageDialog(this, "Datos importados correctamente");
    }
    
    private void insertarUsuario(Usuario u) {
        String sql = "INSERT INTO usuario (id, nombre, apellidos, telefono, correo, usuario, rol) VALUES (?, ?, ?, ?, ?, ?, ?)";
        try (Connection con = Conexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, u.getId());
            ps.setString(2, u.getNombre());
            ps.setString(3, u.getApellidos());
            ps.setString(4, u.getTelefono());
            ps.setString(5, u.getCorreo());
            ps.setString(6, u.getUsuario());
            ps.setString(7, u.getRol());

            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al insertar usuario: " + e.getMessage());
        }
    }
    
    private void insertarMascota(Mascota m) {
        String sql = "INSERT INTO mascota (nombre, especie, edad, sexo, peso, vacunas, historial, id_dueno) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection con = Conexion.getConexion(); PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, m.getNombre());
            ps.setString(2, m.getEspecie());
            ps.setString(3, m.getEdad());
            ps.setString(4, m.getSexo());
            ps.setDouble(5, m.getPeso());
            ps.setBoolean(6, m.isVacunas());
            ps.setString(7, m.getHistorial());
            ps.setString(8, m.getIdDueno());

            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al insertar mascota: " + e.getMessage());
        }
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogInsercionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogInsercionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogInsercionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogInsercionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogInsercionDatos dialog = new JDialogInsercionDatos(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArchivo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
