/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Veterinaria;
import Veterinaria.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author DAM2Alu2
 */
public class JDialogPanel extends javax.swing.JDialog {
    private String usuario;
    private String contrasena;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogPanel.class.getName());

    /**
     * Creates new form Panel
     */
    public JDialogPanel(java.awt.Dialog parent, boolean modal, String usuario, String contrasena) {
        super(parent, modal);
        initComponents();
        ajustarImagenLogo();
        ajustarImagenAdmins();
        ajustarImagenVets();
        this.usuario = usuario;
        this.contrasena = contrasena;
       
        try (Connection con = Conexion.getConexionUsuario(usuario, contrasena)) {
            String sqlUsuario = "SELECT rol FROM usuario WHERE usuario = ?";
            PreparedStatement ps = con.prepareStatement(sqlUsuario);
            ps.setString(1, usuario);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String rol = rs.getString("rol").trim();

                if ("Veterinario".equalsIgnoreCase(rol)) {
                    jButtonAdministradores.setEnabled(false);
                    jButtonVeterinarios.setEnabled(true);
                } else {
                    jButtonVeterinarios.setEnabled(false);
                    jButtonAdministradores.setEnabled(true);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelAdministrador = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelAdmins = new javax.swing.JLabel();
        jButtonAdministradores = new javax.swing.JButton();
        jPanelVeterinario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelVets = new javax.swing.JLabel();
        jButtonVeterinarios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelInformes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 210, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenid@ a la sección para empleados.");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 70, 0));

        jPanelAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAdministrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 211, 183), 5));
        jPanelAdministrador.setLayout(new java.awt.GridLayout(3, 0, 5, 0));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Panel de administrador@s.");
        jPanelAdministrador.add(jLabel2);
        jPanelAdministrador.add(jLabelAdmins);

        jButtonAdministradores.setBackground(new java.awt.Color(52, 164, 175));
        jButtonAdministradores.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButtonAdministradores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdministradores.setText("ENTRAR");
        jButtonAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministradoresActionPerformed(evt);
            }
        });
        jPanelAdministrador.add(jButtonAdministradores);

        jPanel2.add(jPanelAdministrador);

        jPanelVeterinario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVeterinario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 211, 183), 5));
        jPanelVeterinario.setPreferredSize(new java.awt.Dimension(184, 213));
        jPanelVeterinario.setLayout(new java.awt.GridLayout(3, 0, 5, 0));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Panel de veterinari@s.");
        jPanelVeterinario.add(jLabel3);
        jPanelVeterinario.add(jLabelVets);

        jButtonVeterinarios.setBackground(new java.awt.Color(52, 164, 175));
        jButtonVeterinarios.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButtonVeterinarios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVeterinarios.setText("ENTRAR");
        jButtonVeterinarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeterinariosActionPerformed(evt);
            }
        });
        jPanelVeterinario.add(jButtonVeterinarios);

        jPanel2.add(jPanelVeterinario);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout());

        jLabelInformes.setBackground(new java.awt.Color(255, 153, 0));
        jLabelInformes.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabelInformes.setForeground(new java.awt.Color(255, 153, 0));
        jLabelInformes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInformes.setText("VER INFORMES");
        jLabelInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInformesMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelInformes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVeterinariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeterinariosActionPerformed
        JDialogPanelVeterinario vet = new JDialogPanelVeterinario(JDialogPanel.this, true);
        vet.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVeterinariosActionPerformed

    private void jButtonAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministradoresActionPerformed
        JDialogpanelAdministrador ad = new JDialogpanelAdministrador(JDialogPanel.this, true);
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAdministradoresActionPerformed

    private void jLabelInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInformesMouseClicked
        
    }//GEN-LAST:event_jLabelInformesMouseClicked

    /**
     * @param args the command line arguments
     */
    private void ajustarImagenLogo() {
    // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/logoVeterinaria.png")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            logo.getWidth(),
            logo.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        logo.setIcon(iconoEscalado);
    }
    
    private void ajustarImagenAdmins() {
    // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/administradores.jpg")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            jLabelAdmins.getWidth(),
            jLabelAdmins.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        jLabelAdmins.setIcon(iconoEscalado);
    }
    
    private void ajustarImagenVets() {
    // Cargar la imagen original desde los recursos
        javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(
            getClass().getResource("/recursos/veterinarios.jpg")
        );

        // Escalar la imagen al tamaño del JLabel
        java.awt.Image imagenEscalada = originalIcon.getImage().getScaledInstance(
            jLabelVets.getWidth(),
            jLabelVets.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );

        // Crear un nuevo icono con la imagen escalada
        javax.swing.ImageIcon iconoEscalado = new javax.swing.ImageIcon(imagenEscalada);

        // Asignarlo al JLabel
        jLabelVets.setIcon(iconoEscalado);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogPanel dialog = new JDialogPanel(new javax.swing.JDialog(), true, "", "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministradores;
    private javax.swing.JButton jButtonVeterinarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAdmins;
    private javax.swing.JLabel jLabelInformes;
    private javax.swing.JLabel jLabelVets;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAdministrador;
    private javax.swing.JPanel jPanelVeterinario;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}